### ISSUE TITLE
New maintainers for wasm-bindgen-rayon?

### ISSUE THREAD

**Issue by pr1metine** [RReverser/wasm-bindgen-rayon#14]
Hi @RReverser,
its safe to say that this project is extremely useful to all of us WebAssembly / Rust devs. Thank you for this ♥.

However, I could not help but notice that you do not respond to recently created issues and PRs. Of course, you are probably busy with other projects. Therefore, I would like to suggest onboarding new maintainers for this project. While I, myself, do not see myself as a suitable maintainer, I am sure that some contributers would be ready to take on this role.

**Comment by RReverser** [comment]
Hm, I don't think there were many pressing issues.

The most relevant that comes to mind is https://github.com/RReverser/wasm-bindgen-rayon/pull/10#issuecomment-2348938775 which I indeed missed previously, but now it's waiting for the PR author to respond.

I guess I can now merge https://github.com/RReverser/wasm-bindgen-rayon/pull/12 instead.

**Comment by RReverser** [comment]
But yeah, if there are willing users, I don't mind sharing the maintainer rights, as long as they're trustworthy (wouldn't want to turn this into a supply chain vector).

**Comment by RReverser** [comment]
Well, I finally found out why I was missing so many issues and PRs - because this repo was moved over from GoogleChromeLabs org to my personal account, it seems it didn't have "Watch" notifications enabled unless personally pinged 🤦‍♂️

I fixed that now, and should hopefully be able to respond to issues a bit quicker.

**Comment by RReverser** [comment]
I'll close this for now, let's see how it goes.
