### ISSUE TITLE
Problems with Microsoft Edge

### ISSUE THREAD

**Issue by pr1metine** [RReverser/wasm-bindgen-rayon#15]
Hi,
AFAICT, the [Mandelbrot demo for wasm-bindgen-rayon](https://rreverser.com/wasm-bindgen-rayon-demo/) cannot be run on Microsoft Edge Version 129.0.2792.52. Instead, it freezes.

In general, Edge seems to always freak out when running wasm-bindgen-rayon. For example, even if a wasm-bindgen-rayon powered webpage does not freeze, this webpage crashes when opening Edge's DevTools

**Comment by RReverser** [comment]
That's odd, it works fine for me in Edge 129.0.2792.65, only slightly newer than yours. And it worked fine in the past as well.

Might be something with your local environment, but without more details or repro steps it's hard to tell.

**Comment by pr1metine** [comment]
Hmm yeah. I can confirm that it works on Linux + Edge as well. I had some problems with running it on Windows + Edge though. Probably need to investigate this further
