### ISSUE TITLE
Freeze with `wasm-pack` and default flags

### ISSUE THREAD

**Issue by antonWetzel** [RReverser/wasm-bindgen-rayon#8]
The call to `await initThreadPool(...)` did not return with the default feature flags without printing any error or message.
I used the recommended build command for CLI.

Using `features = ["no-bundler"]` resolves the issue.

**Comment by RReverser** [comment]
Sorry, but this issue is a bit useless without a repro.

**Comment by antonWetzel** [comment]
I created a minimal repoduction sample.
<https://github.com/antonWetzel/wrtest>

The configurations are copied from the readme.

**Comment by RReverser** [comment]
Thanks, going to try it out.

**Comment by RReverser** [comment]
Looks like that command requires me to have a Vercel account? Can you just publish it as Github Pages or something please, or at least switch it to standalone HTTP server?

**Comment by RReverser** [comment]
Nevermind, got the index.html itself served with a static HTTP server. So you're using the bundler build mode, but you're not actually using a bundler?

Sadly, yeah, as the docs say, those modes are not interchangeable due to `import` shenanigans. You need to pick one appropriate for your environment, which in your case is `no-bundler`, which works as expected.

**Comment by antonWetzel** [comment]
I read the readme until all compile errors were resolved. So I skipped the `Usage without bundlers` in the `Usage with various bundlers` section.

Bundlers work by default is a reasonable default.
I would prefer if some warning or error (compile or runtime) is thrown, to show me my mistake instead of the freeze.

**Comment by RReverser** [comment]
Just to be clear, freezing is not something we do intentionally, it's just what happens due to incompatibility between those two modes.

If you can send a PR that detects this deadlock and issues a warning, sure, I'd be happy to accept one. (ideally it would be limited to debug builds only though)

**Comment by RReverser** [comment]
Actually, it looks like you do get at least some warnings (although they are obscure) in devtools console:

![image](https://github.com/user-attachments/assets/575c00bc-997f-4f74-8d07-3fd84cce80d4)

**Comment by antonWetzel** [comment]
I get no errors if I test it with vercel, looks like a difference in the serving server.
I might look into a solution, but I am no expert in js/html and servers.

**Comment by RReverser** [comment]
Can you check JS/Wasm resources Network tab?

It might be that loading is failing even earlier in your case if your COOP/COEP headers are not set up correctly. I'm not very familiar with vercel config format, but that could explain it at least.
